version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest  
  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    container_name: microservice-orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile

  authserver.api:
    image: ${DOCKER_REGISTRY-}authserverapi
    container_name: microservice-authserver
    build:
      context: .
      dockerfile: AuthServer.API/Dockerfile

  deliveryserver.api:
    image: ${DOCKER_REGISTRY-}deliveryserverapi
    build:
      context: .
      dockerfile: DeliveryService.API/Dockerfile

volumes:
  sqlserver_volume :
