version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
  authserver.api:
    image: ${DOCKER_REGISTRY-}authserverapi
    container_name: microservice-authserver
    build:
      context: .
      dockerfile: AuthServer.API/Dockerfile
  
volumes:
  sqlserver_volume :