version: '3.4'

services:
  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12*
    volumes:
      - sqlserver_volume:/var/opt/mssql
    ports:
      - "1433:1433"
  orderservice.api:
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production #Production yazanda Docker-de, Development yazanda adi ayaga qaldiririq
    ports:
      - "5010:80"
  authserver.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production #Production yazanda Docker-de, Development yazanda adi ayaga qaldiririq
    ports:
      - "5000:80"
    


    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 
  deliveryserver.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production #Production yazanda Docker-de, Development yazanda adi ayaga qaldiririq
    ports:
      - "5050:80"
