version: '3.4'

services:
  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12
    volumes:
      - sqlserver_volume:/var/opt/mssql
    ports:
      - "1433:1433"

  authserver.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      #- Serilog:WriteTo:0:Args:path=/app/logs/webapi-.log
    ports:
      - "5000:80"
 
  deliveryserver.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5020:80"
    

  orderserver.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5010:80"
  
