version: '3.4'

services:  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    networks:
      - parceldelivery

  authserver.api:
    image: kamrankzade/authserver:${version}
    container_name: authserverapi-container
    volumes:
      - authserver_logs:/app/Logs
    build:
      context: .
      dockerfile: AuthServer.API/Dockerfile
    networks:
      - parceldelivery

  deliveryserver.api:
    image: kamrankzade/deliveryserver:${version}
    container_name: deliveryserverapi-container
    volumes:
      - deliveryserver_logs:/app/Logs
    build:
      context: .
      dockerfile: DeliveryService.API/Dockerfile
    networks:
      - parceldelivery


  orderserver.api:
    image: kamrankzade/orderserver:${version}
    container_name: orderserverapi-container
    volumes:
      - orderserver_logs:/app/Logs
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    networks:
      - parceldelivery
        

  parceldeliverygateway:
    image: kamrankzade/parceldeliverygateway:${version}
    container_name: parceldeliverygateway-container
    build:
      context: .
      dockerfile: ParcelDeliveryGateway/Dockerfile
    networks:
     - parceldelivery
    depends_on:
     - authserver.api
     - orderserver.api
     - deliveryserver.api

volumes:
  sqlserver_volume :
  authserver_logs : 
  orderserver_logs : 
  deliveryserver_logs :

networks:
  parceldelivery:
